#!/usr/bin/env bash
set -e

# ステージされている、README等以外の全てのMarkdownファイルを対象とする。
files=$(
  git diff --name-only --cached --diff-filter d |
  grep '\.md' |
  grep -v 'README\.md' |
  grep -v '/_sidebar.md'|
  sed 's/\"//'
)
[ -z "$files" ] && exit

# 各種対象ファイルについてチェックを行う。
echo "$files" | xargs markdownlint -f
md-h1 -f "$files"
git add "$files"
