#!/usr/bin/env bash
set -e

cd "$(dirname "$0")/.."

# ステージされているファイルのうち、削除されていないものについて、フォーマットをチェックする。
files=$(
  git diff --name-only --cached --diff-filter d |
    grep '\.md' |
    grep -v 'README\.md' |
    grep -v '/_sidebar.md' |
    cat
)
if [ -n "$files" ]; then
  # フォーマットを綺麗にする。
  echo "$files" | tr '\n' '\0' | xargs -0 markdownlint -f
  echo "$files" | tr '\n' '\0' | xargs -0 md-h1 -f
  echo "$files" | tr '\n' '\0' | xargs -0 git add
fi

# ステージされているファイルのうち、追加・削除・リネームが行われたものが存在するディレクトリについて、連番を綺麗にする。
# TODO 最下部のディレクトリのみに対して処理を行うようにしたい。
directories=$(
  git diff --name-only --cached --diff-filter m |
    grep '\.md' |
    grep -v 'README\.md' |
    grep -v '/_sidebar.md' |
    cut -d / -f 1-2 |
    sort |
    uniq
)
if [ -n "$directories" ]; then
  # 連番を綺麗にする。
  echo "$directories" | tr '\n' '\0' | xargs -0 fn-update
  echo "$directories" | tr '\n' '\0' | xargs -0 git add

  # サイドバーを再生成する。
  # docsディレクトリからの相対パスで生成したいため、cdする。
  (
    cd docs
    md-tree | grep -v '_sidebar\.md' | grep -v 'README\.md' >_sidebar.md
    git add _sidebar.md
  )
fi
