#!/usr/bin/env bash
set -e

# ステージされているファイルのうち、削除されていないものについて、フォーマットをチェックする。
files=$(
  git diff --name-only --cached --diff-filter d |
    grep '\.md' |
    grep -v 'README\.md' |
    grep -v '/_sidebar.md' |
    sed 's/\"//'
)
if [ -n "$files" ]; then
  # フォーマットを綺麗にする。
  echo "$files" | xargs markdownlint -f
  echo "$files" | xargs md-h1 -f

  # ステージする。
  echo "$files" | xargs git add
fi

# ステージされているファイルのうち、追加・削除・リネームが行われたものが存在するディレクトリについて、連番を綺麗にする。
# TODO 最下部のディレクトリのみに対して処理を行うようにしたい。
directories=$(
  git diff --name-only --cached --diff-filter m |
    grep '\.md' |
    grep -v 'README\.md' |
    grep -v '/_sidebar.md' |
    sed 's/\"//' |
    cut -d / -f 1-2 |
    sort |
    uniq
)
if [ -n "$directories" ]; then
  # 連番を綺麗にする。
  # TODO fn-updateに複数の引数を渡せるようにする
  while read -r directory; do
    fn-update "$directory"
  done <<<"$directories"

  # サイドバーを再生成する。
  # docsディレクトリからの相対パスで生成したいため、cdする。
  (
    cd "$(dirname "$0")/docs"
    md-tree | grep -v '_sidebar\.md' | grep -v 'index\.html' >_sidebar.md
  )

  # ステージする。
  echo "$directories" | xargs git add
  git add "$(dirname "$0")/../docs/_sidebar.md"
fi
